version: '3'
services:
  web:
    build: .
    ports:
      - "90:80"
    volumes:
      - /Users/in-mayank.vaid/apacheconf/sites:/usr/local/apache2/conf/sites
      - /Users/in-mayank.vaid/apacheconf/htmlfiles:/usr/local/apache2/ebs
    networks:
      - app_net
  ebs_login_db1:
    image: "mysql"
    volumes:
      - ./mysql/replication1.cnf:/etc/mysql/conf.d/replication1.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
  ebs_login_db2:
    image: "mysql"
    volumes:
      - ./mysql/replication2.cnf:/etc/mysql/conf.d/replication2.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
  ebs_login_db3:
    image: "mysql"
    volumes:
      - ./mysql/replication3.cnf:/etc/mysql/conf.d/replication3.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
  client:
    image: "mysql"
    command: bash -c "./runDBScript.sh ebs_login_db1 3306 master_bootstrap_replication.sql && ./runDBScript.sh ebs_login_db2 3306 master_replication.sql && ./runDBScript.sh ebs_login_db3 3306 master_replication.sql && ./runDBScript.sh ebs_login_db1 3306 setup_ebs_db.sql"
    volumes:
      - ./mysql/master_bootstrap_replication.sql:/master_bootstrap_replication.sql
      - ./mysql/master_replication.sql:/master_replication.sql
      - ./mysql/setup_ebs_db.sql:/setup_ebs_db.sql
      - ./scripts/runDBScript.sh:/runDBScript.sh
    networks:
      - app_net
  haproxy:
    build: ./haproxy/
    ports:
      - "36930:36936"
      - "8089:8089"
    networks:
      - app_net
  app:
    build: ./EBS-Login/
    depends_on:
      - ebs_login_db1
      - ebs_login_db2
      - ebs_login_db3
      - web
      - haproxy
    ports:
      - "8080:8080"
    networks:
      - app_net
networks:
  app_net:
    driver: "bridge"
