version: '3'
services:
  jaeger_query:
    image: "jaegertracing/jaeger-query"
    ports:
      - "16686:16686"
      - "16687:16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
    networks:
      - ebs_app_net
  jaeger_collector:
    image: "jaegertracing/jaeger-collector"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
    networks:
      - ebs_app_net
  jaeger_agent:
    image: "jaegertracing/jaeger-agent"
    command: ["--reporter.grpc.host-port=jaeger_collector:14250"]
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    networks:
      - ebs_app_net
networks:
  ebs_app_net:
    external: true