version: '3'
services:
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.8.0"
    ports:
      - "5601:5601"
    volumes:
      - /Users/in-mayank.vaid/Projects/EBS/infra/logging/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - ebs_app_net
  elastic_search:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - ebs_app_net
  kafka:
    image: "spotify/kafka:latest"
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    networks:
      - ebs_app_net
  logstash:
    image: "logstash:7.8.0"
    volumes:
    - /Users/in-mayank.vaid/Projects/EBS/infra/logging/logstash/pipeline/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
    - /Users/in-mayank.vaid/Projects/EBS/infra/logging/logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - ebs_app_net
networks:
  ebs_app_net:
    external: true