version: '3'
services:
  db:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./db-migrations/init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app_net
networks:
  app_net:
    driver: "bridge"
