spring:
  application:
    name: ebs-login
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:replication://haproxy:36936/ebs
    username: root
    password: root
    hikari:
      initializationFailTimeout: 100000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
server:
  port: 8080
  servlet:
    contextPath: /ebs-login
eureka:
  client:
    service-url:
      defaultZone: http://ebseurekaserver:8080/eureka
  instance:
    preferIpAddress: false